
server:
  port: 8085

spring:
  application:
    name: recipes

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            lucene:
              analysis:
                configurer: class:org.hibernate.search.backend.lucene.analysis.LuceneAnalysisConfigurer
            directory:
              type: local-filesystem
              root: ./target/lucene/indexes
          automatic_indexing:
            enabled: true
            synchronization_strategy: sync

  h2:
    console:
      enabled: true

api:
  retry:
    max-attempts: 3
    min-backoff: 1
    max-backoff: 5

logging:
  level:
    root: DEBUG  # Enables detailed logs for development
